# CI — [PROJECT_NAME]

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "[PYTHON_VERSION]"
  UV_CACHE_DIR: .uv_cache

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Ruff check
        run: uv run ruff check .

      - name: Ruff format check
        run: uv run ruff format --check .

      - name: Mypy
        run: uv run mypy .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    # services:
    #   postgres:
    #     image: postgres:16-alpine
    #     env:
    #       POSTGRES_DB: [DB_NAME]
    #       POSTGRES_USER: [DB_USER]
    #       POSTGRES_PASSWORD: test
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd "pg_isready"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #   redis:
    #     image: redis:7-alpine
    #     ports:
    #       - 6379:6379
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest --cov=[PACKAGE] --cov-report=term-missing

  # build:
  #   name: Docker build
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v5
  #
  #     - name: Build image
  #       run: |
  #         docker build \
  #           --build-arg VERSION="${{ github.ref_name }}" \
  #           --build-arg VCS_REF="${{ github.sha }}" \
  #           -t [APP_NAME]:${{ github.sha }} .
